### ISSUE TITLE
Support `osx`

### ISSUE THREAD

**Issue by chenglong-do** [agilewalker/SwiftyChardet#1]
The platform of the target `TxtRenamer` (OS X 10.11) is not compatible with `SwiftyChardet (1.0.0)`, which does not support `osx`.

Clud you please make it support osx?

Thanks!

**Comment by agilewalker** [comment]
Thank you for your feedback!  Mind you this is a highly experimental project and currently with a much-longer-than-usual compile time until Swift compiler could be more efficiently compiling with large array literals.
Anyway [https://github.com/agilewalker/SwiftyChardet/tree/1.0.2](https://github.com/agilewalker/SwiftyChardet/tree/1.0.2) is now available with fix for OSX. Please try it. Due to heavy git code rebase, you might have to delete Pods/ folder under you project and do 'pod update' again.

**Comment by chenglong-do** [comment]
Thanks very much!
